### PR TITLE
 fix: insert column/row buttons not working

### PR DESCRIPTION
**Pull request by johnny243**
Fixes https://github.com/standardnotes/secure-spreadsheets/issues/12 and https://github.com/standardnotes/forum/issues/386

### CODE REVIEW

**Comment by johnny243** [comment]
Actually, I think the previous code tried to insert the column/row AND increase the column/row by one.

---

So far, this PR has the following features/fixes:

- [x] ability to use the insert column/row buttons
- [ ] when inserting columns/rows, the columns/rows number should be increased

**Comment by bryvin** [comment]
Hi Johnny,

Hope all is well! A year ago I had messed with fixing this and I believe I had a working solution which I have up here on a commit: https://github.com/bryvin/secure-spreadsheets/commit/3648c177dd1d65a7cb02047f2a81c21dad34d65f

Maybe this can be of some help, it's a bit hacky but with the way KendoUI loads/renders the spreadsheets it was a little difficult to adjust the size after it had been rendered. So hijacking the render call after using one of the built in events to insert a row/column and triggering a fresh build of the sheet from the JSON data on the next render with the new size seemed to have fixed it.

**Comment by johnny243** [comment]
Hi @bryvin!

Thanks for letting me know about your fix, it's working great so far!

**Comment by bryvin** [comment]
I was under the impression this wasn't originally merged back in January due to all undo history being removed when rebuilding the sheet after inserting/removing rows and columns. Was that fixed at all?

**Comment by johnny243** [comment]
Hey @bryvin, before version 1.3.7, the undo/redo buttons did not work after inserting/removing columns or rows. So merging this PR will not break the undo/redo buttons.

**Comment by bryvin** [comment]
Ah, perfect then! Glad you got this in :)

**Pull request merged**
